# These are supported funding model platforms

github: # [YoutacRandS-VA, user2]
patreon: # patreon.com/user?u=107365027
custom: # ['youtacrs.wordpress.com', 'youtacrs8.wordpress.com']
open_collective: webpack
